before:
  hooks:
    - go mod download
builds:
  - id: "tgscli"
    env:
      - CGO_ENABLED=0
    main: ./cmd/tgscli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    # dir:
    binary: tgscli
archives:
  - id: default
    # name_template: "tgscli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - tgscli
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
