name: goreleaser

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      VERSION_IMPORT: github.com/huangnauh/tgcli/version
      GIT_COMMIT: $(git rev-parse --short HEAD)
      GIT_DESCRIBE: $(git rev-parse --short HEAD)
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}